processes:
  - name: temp_tank1
    model: first_order
    parameters:
      tau: 30
      ambient: 25
      capacity: 100
    initial_value: 25
    controller:
      type: PID
      setpoint: 70
      Kp: 2.0
      Ki: 0.1
      Kd: 0.2
      output_limits: [0, 100]
      controlled_by: heater1
  - name: temp_tank2
    model: first_order
    parameters:
      tau: 50
      ambient: 25
      capacity: 120
    initial_value: 25
    controller:
      type: P
      setpoint: 60
      Kp: 1.5
      output_limits: [0, 100]
      controlled_by: heater2
